// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUbNZKc_V5KB0O8yziywojAhNrcsSHTnE',
    appId: '1:293392169137:web:ba37843e09c42a0633ca90',
    messagingSenderId: '293392169137',
    projectId: 'imc-d-94fa0',
    authDomain: 'imc-d-94fa0.firebaseapp.com',
    storageBucket: 'imc-d-94fa0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK1LsbG_lRZJON9LjFsrz2FnuM3Swym0E',
    appId: '1:293392169137:android:ec92b659350ede8233ca90',
    messagingSenderId: '293392169137',
    projectId: 'imc-d-94fa0',
    storageBucket: 'imc-d-94fa0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl6wu6W7sWiPD353EqixMkEjbstvhFROQ',
    appId: '1:293392169137:ios:95ddf4390597216a33ca90',
    messagingSenderId: '293392169137',
    projectId: 'imc-d-94fa0',
    storageBucket: 'imc-d-94fa0.firebasestorage.app',
    iosBundleId: 'com.example.imcSecured',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl6wu6W7sWiPD353EqixMkEjbstvhFROQ',
    appId: '1:293392169137:ios:95ddf4390597216a33ca90',
    messagingSenderId: '293392169137',
    projectId: 'imc-d-94fa0',
    storageBucket: 'imc-d-94fa0.firebasestorage.app',
    iosBundleId: 'com.example.imcSecured',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUbNZKc_V5KB0O8yziywojAhNrcsSHTnE',
    appId: '1:293392169137:web:dd1cc75ea8c00e5233ca90',
    messagingSenderId: '293392169137',
    projectId: 'imc-d-94fa0',
    authDomain: 'imc-d-94fa0.firebaseapp.com',
    storageBucket: 'imc-d-94fa0.firebasestorage.app',
  );
}
